version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: "crm_web"
    tty: true
    ports:
      - "9000:9000"
    networks:
      - default
    volumes:
      - .:/app
  nginx:
    image: nginx:1.10.3
    container_name: "crm_nginx"
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    links:
      - web